function a = axisgui(AxesTag)
%AXISGUI - GUI for changing axis properties
%  FigureHandle = axisgui(AxesHandle)
%
%  Creates a GUI to change axis (and view if 3-D plot) parameters of 
%  the axes referenced by AxesHandle.  AxesHandle can be an axes handle, 
%  axes tag, or left blank.  If blank or a tag, the current axis (gca) 
%  will be used.  If no axis exists, then one will be created.  
%  FigureHangle is the handle to the figure created by this function.
%
%  See also axismenu
%
%  Written by Greg Portmann (May 1997)

% Calls:  axisfn

if nargin < 1
   % This will create an axis if one does not exist
   AxesTag=gca;
end

if isstr(AxesTag)
   AxesHandle = findobj(gcf,'Tag',AxisTag);
   if length(AxesHandle) > 1
      AxesHandle = AxesHandle(1);
   end
else
   AxesHandle = AxesTag;
end

if isnan(AxesHandle)
   return;
end

%FigHandle=get(AxesHandle,''Parent'');

a = figure( ...
   'CreateFcn','set(gca,''visible'',''off'');', ...
   'Color',[0.8 0.8 0.8], ...
   'DeleteFcn','set(findobj(get(get(gcbf,''Userdata''),''Parent''),''Tag'',''MenuAxisTool''),''Checked'',''off'');', ...
   'Interruptible','off', ...
   'MenuBar','None', ...
   'Name','Resize', ...
	'NumberTitle','off', ...
   'Units','Normal', ...
   'Position',[.05 .7 .1 .1], ...
   'Resize','off', ...
   'Visible','off', ...
   'Userdata', AxesHandle);  % Axis handle of which the axis tool is working on

%b = uicontrol('Parent',a, ...
%	'BackgroundColor',[0.8 0.8 0.8], ...
%   'Callback','axisfn(''Initialize'');', ...
%	'Units','points', ...
%   'Interruptible','off', ...
%	'Position',[2 2 50 17.25], ...
%	'String','Update', ...
%	'Tag','Update');

%    'Position',[52 2 50 17.25], ...

b = uicontrol('Parent',a, ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','axisfn(''AutoScale'');', ...
   'Units','points', ...
   'Interruptible','off', ...
   'Position',[2 2 40.5 17.25], ...
	'String','Auto scale', ...
   'Tag','AutoScale');

%   'Position',[102 2 50 17.25], ...
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','close(gcbf);', ...
	'Units','points', ...
   'Interruptible','off', ...
   'Position',[102 2 50 17.25], ...
   'String','Close', ...
	'Tag','CloseAxisGUI');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[2 21 30 13], ...
	'String','Zmin =', ...
	'Style','text', ...
	'Tag','TextZmin');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''ChangeAxis'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[32.5 21 40 13], ...
	'Style','edit', ...
	'Tag','EditZmin');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[78.75 21.75 30 13.5], ...
	'String','Zmax =', ...
	'Style','text', ...
	'Tag','TextZmax');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''ChangeAxis'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[108.75 21.75 40.5 13.5], ...
	'Style','edit', ...
   'Tag','EditZmax');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Units','points', ...
	'Position',[1.5 37.5 30 13.5], ...
   'Interruptible','off', ...
	'String','Ymin =', ...
	'Style','text', ...
   'Tag','TextYmin');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''ChangeAxis'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[31.5 37.5 40.5 13.5], ...
	'Style','edit', ...
	'Tag','EditYmin');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[76.5 36.75 30 13.5], ...
	'String','Ymax =', ...
	'Style','text', ...
	'Tag','TextYmax');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''ChangeAxis'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[106.5 36.75 40.5 13.5], ...
	'Style','edit', ...
	'Tag','EditYmax');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[1.5 55.5 30 13.5], ...
	'String','Xmin =', ...
	'Style','text', ...
	'Tag','TextXmin');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''ChangeAxis'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[31.5 55.5 40.5 13.5], ...
	'Style','edit', ...
	'Tag','EditXmin');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[78 52.5 30 13.5], ...
	'String','Xmax =', ...
	'Style','text', ...
	'Tag','TextXmax');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''ChangeAxis'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[108 52.5 40.5 13.5], ...
	'Style','edit', ...
	'Tag','EditXmax');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[108 52.5 40.5 13.5], ...
	'String','Rotate Horizontally', ...
	'Style','text', ...
	'Tag','TextHorizontal');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''RotateHorizontal'');', ...
   'Max',  180,...
   'Min', -180,...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[108 52.5 40.5 13.5], ...
   'Style','slider', ...
   'SliderStep',300/361*[.01 .05], ...
   'Tag','SliderHorizontal');

b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[1 52.5 40.5 13.5], ...
	'String','Rotate Vertically', ...
	'Style','text', ...
	'Tag','TextVertical');
b = uicontrol('Parent',a, ...
   'BackgroundColor',[1 1 1], ...
   'Callback','axisfn(''RotateVertical'');', ...
   'Max',  90,...
   'Min', -90,...
	'Units','points', ...
   'Interruptible','off', ...
   'Position',[1 52.5 40.5 13.5], ...
   'SliderStep',300/181*[.01 .05], ...
	'Style','slider', ...
   'Tag','SliderVertical');


b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'CreateFcn','axisfn(''Initialize'');', ...
	'Units','points', ...
   'Interruptible','off', ...
	'Position',[5.25 72.75 143.25 14.25], ...
	'String','Enter new axis dimension and hit return', ...
	'Style','text', ...
	'Tag','TextHeader');
