function mml2edm_mps(Directory)

DirStart = pwd;

if nargin < 1
    if ispc
        cd \\Als-filer\physbase\hlc\BTS
    else
        cd /home/als/physbase/hlc/BTS
    end
else
    cd(Directory);
end


WindowLocation = [120 60];
FileName = 'MML2EDM_BTS_MPS.edl';
TitleBar = 'BTS Magnet Power Supplies';
GoldenSetpoints = 'On';
MotifWidget = 'Off';
SP_AM = 'On';
BG = 62;  % LTB=, BR=, BTS=62, SR=4  (Note: TextControl BG=0)

ChannelLabelWidth = 70;

%ChannelLabelWidth = 60;
%'ChannelLabelWidth', ChannelLabelWidth, ...


[x11, y11]= mml2edm('HCM', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'xStart', 0, ...
    'yStart', 0*5, ...
    'SP-AM', SP_AM, ...
    'SP_BackgroundColor', BG-2, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'Horizontal Correctors', ...
    'TitleBar', TitleBar);
   %'Fields', {'Setpoint','Monitor','Ready','On','OnControl'}, ...

[x21, y21]= mml2edm('VCM', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y11+20, ...
    'SP-AM', SP_AM, ...
    'SP_BackgroundColor', BG-2, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'Vertical Correctors', ...
    'TitleBar', TitleBar);
   %'Fields', {'Setpoint','Monitor','Ready','On','OnControl'}, ...

[x12, y12]= mml2edm('BEND', ...
    'FileName', FileName, ...
    'Fields', {'Setpoint','Monitor','Ready','On','OnControl','Reset'}, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', x21+25, ...
    'yStart', 35, ...
    'SP-AM', SP_AM, ...
    'SP_BackgroundColor', BG-2, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'Bends', ...
    'TitleBar', TitleBar);

%  Not using SP-AM column because quadrupoles have "," in the name
[x22, y22]= mml2edm('Q', ...
    'FileName', FileName, ...
    'Fields', {'Setpoint','Monitor','Ready','On','OnControl','Reset'}, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', x21+25, ...
    'yStart', y12+40, ...
    'SP_BackgroundColor', BG-2, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'Quadrupoles', ...
    'TitleBar', TitleBar);

x31 = 0;
y31 = 0;
% [x31, y31]= mml2edm('SOL', ...
%     'FileName', FileName, ...
%     'Append', ...
%     'xStart', 0, ...
%     'yStart', y21+20, ...
%     'WindowLocation', [120 60], ...
%     'TitleBar', TitleBar);

x32=0;
y32=0;


% Add push buttons for other applications
edm_addinjectorbuttons(0, y21+20, FileName);


xmax = max([x11 x21 x12 x22 x31 x32]);
ymax = max([y11 y21 y12 y22 y31 y32]);
% if  ymax > 1200 %  I'm not sure when the slider appears
%     % To account for a window slider
%     Width  = xmax+30;
%     Height = 1220;
% else
     Width  = xmax + 10;
     Height = ymax + 20+40;
% end

%EDMExitButton(xmax-68, 3, 'FileName', FileName);  % 'ExitProgram'

Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height, 'BackgroundColor',BG);


cd(DirStart);
