function mml2edm_pulsedmagnets(Directory)

DirStart = pwd;

if nargin < 1
    if ispc
        cd \\Als-filer\physbase\hlc\BTS
    else
        cd /home/als/physbase/hlc/BTS
    end
else
    cd(Directory);
end


WindowLocation = [120 60];
FileName = 'MML2EDM_BTS_PULSED_MAGNETS.edl';
TitleBar = 'BTS Pulsed Magnets';
GoldenSetpoints = 'On';
BC_SetAllButton = 'Off';
SP_SetAllButton = 'Off';
MotifWidget = 'On';
ChannelLabelWidth = 135;

[x11, y11]= mml2edm( ...
    'Kicker', ...
    'TableTitle', 'BR Kickers', ...
    'Fields', {'Setpoint','Monitor'}, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0*20, ...
    'WindowLocation', [120 60], ...
    'BC_SetAllButton', BC_SetAllButton, ...
    'SP_SetAllButton', SP_SetAllButton, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TitleBar', TitleBar);

[x21, y21]= mml2edm( ...
    'BRBump', ...
    'TableTitle', 'BR Bumps', ...
    'Fields', {'Setpoint','Monitor'}, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y11+20, ...
    'WindowLocation', [120 60], ...
    'BC_SetAllButton', BC_SetAllButton, ...
    'SP_SetAllButton', SP_SetAllButton, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TitleBar', TitleBar);

[x31, y31]= mml2edm(...
    'Septum', ...
    'TableTitle', 'Septum Magnets', ...
    'Fields', {'Setpoint','Monitor'}, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y21+20, ...
    'WindowLocation', [120 60], ...
    'BC_SetAllButton', BC_SetAllButton, ...
    'SP_SetAllButton', SP_SetAllButton, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TitleBar', TitleBar);

[x41, y41]= mml2edm( ...
    'SRBump', ...
    'TableTitle', 'SR Bumps', ...
    'Fields', {'Setpoint','Monitor'}, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y31+20, ...
    'WindowLocation', [120 60], ...
    'BC_SetAllButton', BC_SetAllButton, ...
    'SP_SetAllButton', SP_SetAllButton, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TitleBar', TitleBar);



xmax = max([x11 x21 x31 x41]);
ymax = max([y11 y21 y31 y41]);

Width  = xmax + 10;
Height = ymax + 0*10;

%EDMExitButton(xmax-68, 3, 'FileName', FileName, 'ExitProgram');

Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



cd(DirStart);
