%function runbts(varargin)
% load the nominal currents in the BTS

bts_pv_names={...
'PS-BA-3-1:CURRENT_MONITOR' [145.54];...
'PS-BA-3-2:CURRENT_MONITOR' [145.54];...
'PS-BA-3-3:CURRENT_MONITOR' [145.54];...
'PS-BA-3-4:CURRENT_MONITOR' [145.54];...
% 'PS-SEP-A-3:CURRENT_MONITOR' [];...
% 'PS-SEP-B-3:CURRENT_MONITOR' [];...
'PS-OC-3-1:CURRENT_MONITOR' [0];...
'PS-OC-3-2:CURRENT_MONITOR' [0];...
'PS-OC-3-3:CURRENT_MONITOR' [0];...
'PS-OC-3-4:CURRENT_MONITOR' [0];...
'PS-OC-3-5:CURRENT_MONITOR' [0];...
'PS-QFA-3-1:CURRENT_MONITOR' [78.86];...
'PS-QFA-3-2:CURRENT_MONITOR' [85.36];...
'PS-QFA-3-3:CURRENT_MONITOR';...
% QFA-3-4 dead 1/6/2006 
%'PS-QFA-3-4:CURRENT_MONITOR';...
'PS-QFA-3-5:CURRENT_MONITOR';...
'PS-QFA-3-6:CURRENT_MONITOR';...
'PS-QFA-3-7:CURRENT_MONITOR';...
'PS-QFA-3-8:CURRENT_MONITOR';...
'PS-QFB-3-1:CURRENT_MONITOR' [113.66];...
'PS-QFB-3-2:CURRENT_MONITOR';...
'PS-QFB-3-3:CURRENT_MONITOR';...
'PS-QFC-3-1:CURRENT_MONITOR';...
};


for i=1:length(bts_pv_names)
    name = bts_pv_names{i};
    h = mcaopen(name);
    if h==0
        fprintf('%s fialed to open channel\n', name);
    else
        fprintf('%s channle opened\n', name);
    end
end
