initialisations = ['global THERING;',...
    'qfaind = getfamilydata(''QFA'',''AT'',''ATIndex'',[11 2; 12 1]);',...
    'qdaind = getfamilydata(''QDA'',''AT'',''ATIndex'',[11 2; 12 1]);',...
    'sfbind = getfamilydata(''SFB'',''AT'',''ATIndex'');';

varget = {'getcellstruct(THERING,''K'',qfaind)';...
          'getcellstruct(THERING,''K'',qdaind)'};
      
% varset = {'THERING = setcellstruct(THERING,''PolynomB'',qfaind,variable,2); THERING = setcellstruct(THERING,''K'',qfaind,variable);';... 
%           'THERING = setcellstruct(THERING,''PolynomB'',qdaind,variable,2); THERING = setcellstruct(THERING,''K'',qdaind,variable);'};  
varset = {'THERING = setcellstruct(THERING,''K'',qfaind,variable);';... 
          'THERING = setcellstruct(THERING,''K'',qdaind,variable);'};  

      
paramget = {'std(machine_at(THERING,0,sfbind,''betax''))';...
            'std(machine_at(THERING,0,sfbind,''betay''))'};
        
goalparam = [0 0];

linearfit(varget,varset,paramget,goalparam,initialisations);