function createlegend(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes
 
%  Auto-generated by MATLAB on 23-Nov-2005 16:50:20
 
%% Create legend
legend1 = legend(axes1,{'Measure','theoritical'},'Position',[0.5934 0.7352 0.1738 0.1706]);
 
