%MEXCOMMAND Make mcamain.dll from mcamain.cpp
% All options are enecessary to compile properly

% Using local CA dll's
%  mex mcamain.cpp D:\Epics\base\lib\Win32\Com.lib...
%      D:\Epics\base\lib\Win32\ca.lib -DDB_TEXT_GLBLSOURCE ...
%      -D_WIN32 -DEPICS_DLL_NO ...     
%      -ID:\Epics\base\include...
%      -ID:\Epics\base\include\os\WIN32 ...
%      -v

%Using CA libraries on the network drive Q:
% mex mcamain.cpp R:\EPICS\R3.14.0beta1\base\lib\win32-x86\Com.lib...
%     R:\EPICS\R3.14.0beta1\base\lib\win32-x86\ca.lib -DDB_TEXT_GLBLSOURCE ...
%     -D_WIN32 -DEPICS_DLL_NO ...     
%     -IR:\EPICS\R3.14.0beta1\base\include ...
%     -IR:\EPICS\R3.14.0beta1\base\include\os\WIN32 ...
%     -v
% 
% 
mex mcamain.cpp R:\EPICS\R3.14.0beta1\base\lib\win32-x86\Com.lib ...
    R:\EPICS\R3.14.0beta1\base\lib\win32-x86\ca.lib ...
    -DDB_TEXT_GLBLSOURCE ...
    -D_WIN32 -DEPICS_DLL_NO...
    -IR:\EPICS\R3.14.0beta1\base\include ...
    -IR:\EPICS\R3.14.0beta1\base\include\os\WIN32 ...
    -v

