%MEXCOMMAND Make mca.dll and timereval.dll
%

cd C:\Matlab2007a\toolbox\mca\

mex mca.cpp MCAError.cpp Channel.cpp ...
            C:\epics\base\lib\win32-x86\Com.lib ...
            C:\epics\base\lib\win32-x86\ca.lib ...
            -DDB_TEXT_GLBLSOURCE -DMSCC -DEPICS_DLL_NO ...
            -DWIN32 ...
            -IC:\epics\base\include ...
            -IC:\epics\base\include\os\WIN32 ...
            -v

mex timereval.cpp -v -DWIN32