Description of family2atindex
Home > at > family2atindex.m
family2atindex
PURPOSE
FAMILY2ATINDEX - Returns the AT index for a given family
SYNOPSIS
function [ATIndexList, ErrorFlag] = family2atindex(Family, varargin)
DESCRIPTION
FAMILY2ATINDEX - Returns the AT index for a given family
  ATIndexList = family2atindex(Family, DeviceList)
  INPUTS
  1. Family - Family Name
              Accelerator Object
              Cell Array of Accelerator Objects or Family Names
              AT FamName (or 'All' every AT index)
  2. DeviceList - Device list {Default: the entire family (familydev('Family',0))}
  OUTPUTS
  1. ATIndexList - List of AT indexes referenced to THERING
                   If the family a split magnet, then muliply columns will be output
  NOTES
  1. If Family is a cell array, then DeviceList must also be a cell array
  2. If using AT FamName, then DeviceList is index vector, ie,
              Length = THERING{ATIndexList}.Length(DeviceList)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atindex2family ATINDEX2FAMILY - Returns the AT index for a given family
calccoupling CALCCOUPLING - Calculates the coupling and tilt of the AT model
drawlattice DRAWLATTICE - Draws the AT lattice to a figure
drawlattice2d DRAWLATTICE2D - Draws the AT lattice to a figure
getatfield GETATFIELD - Returns the contents of an AT model field
getpassmethod GETPASSMETHOD - Gets the PassMethod field
getpvmodel GETPVMODEL - Get the model value
getturns GETTURNS - Single particle tracking for multiple turns
linepass1turn LINEPASS1TURN - Track particle forward or backwards in one turn of the ring
modeldisp MODELDISP - Returns the dispersion function of the model
modelsextu_off MODELSEXTU_OFF - Turns on sextupoles in the AT model
modelsextu_on MODELSEXTU_ON - Turns on sextupoles in the AT model
modeltwiss MODELTWISS - Returns a twiss function of the model
quadroll locate quadrupoles in AO and apply random roll about s-axis
setatfield SETATFIELD - Returns the contents of an AT model field
setpassmethod SETPASSMETHOD - Sets the PassMethod
setpvmodel SETPVMODEL - Sets the model
SOURCE CODE
function [ATIndexList, ErrorFlag] = family2atindex(Family, varargin)
%FAMILY2ATINDEX - Returns the AT index for a given family
%  ATIndexList = family2atindex(Family, DeviceList)
%
%  INPUTS
%  1. Family - Family Name
%              Accelerator Object
%              Cell Array of Accelerator Objects or Family Names
%              AT FamName (or 'All' every AT index)
%  2. DeviceList - Device list {Default: the entire family (familydev('Family',0))}
%
%  OUTPUTS
%  1. ATIndexList - List of AT indexes referenced to THERING
%                   If the family a split magnet, then muliply columns will be output
%
%  NOTES
%  1. If Family is a cell array, then DeviceList must also be a cell array
%  2. If using AT FamName, then DeviceList is index vector, ie,
%              Length = THERING{ATIndexList}.Length(DeviceList)
%  Written by Greg Portmann
ErrorFlag = 0;
if nargin == 0,
    error('Must have at least one input (Family or Channel Name).');
end
[ATIndexList, ErrorFlag] = getfamilydata(Family, 'AT', 'ATIndex', varargin{:});
if isempty(ATIndexList)
    % Try an AT family
    global THERING
    if strcmpi(Family, 'All')
        ATIndexList = (1:length(THERING))';
    else
        ATIndexList = findcells(THERING, 'FamName', Family);
        ATIndexList = ATIndexList(:);
    end
    if nargin >= 2
        if ~isempty(varargin{1})
            if size(varargin{1},2) == 2
                varargin{1} = varargin{1}(:,2);
            end
            ATIndexList = ATIndexList(varargin{1});
        end
    end
end