Description of getcavity
Home > at > getcavity.m
getcavity
PURPOSE
GETCAVITY - Returns the RF cavity state ('On' / 'Off')
SYNOPSIS
function [CavityState, PassMethod, ATCavityIndex, RF, HarmonicNumber] = getcavity(THERING)
DESCRIPTION
GETCAVITY - Returns the RF cavity state ('On' / 'Off')
  [CavityState, PassMethod, ATCavityIndex, RF, HarmonicNumber] = getcavity(THERING)
  OUTPUTS
  1. CavityState
  2. PassMethod
  3. ATCavityIndex - AT Index of the RF cavities
  4. RF - RF frequency [Hz]
  5. HarmonicNumber - Harmonic number
  See also setcavity, setradiation
CROSS-REFERENCE INFORMATION
This function calls:
getharmonicnumber GETHARMONICNUMBER - Returns the harmonic number from the AT model
This function is called by:
calccoupling CALCCOUPLING - Calculates the coupling and tilt of the AT model
concatenaterings
getpvmodel GETPVMODEL - Get the model value
iscavityon ISCAVITYON - True is there is a powered cavity in THERING
modelchro MODELCHRO - Returns the AT model chromaticity
modeldisp MODELDISP - Returns the dispersion function of the model
modeltune MODELTUNE - Returns the model tune (2x1 vector)
SOURCE CODE
function [CavityState, PassMethod, ATCavityIndex, RF, HarmonicNumber] = getcavity(THERING)
%GETCAVITY - Returns the RF cavity state ('On' / 'Off')
%  [CavityState, PassMethod, ATCavityIndex, RF, HarmonicNumber] = getcavity(THERING)
%
%  OUTPUTS
%  1. CavityState
%  2. PassMethod
%  3. ATCavityIndex - AT Index of the RF cavities
%  4. RF - RF frequency [Hz]
%  5. HarmonicNumber - Harmonic number
%
%  See also setcavity, setradiation
%  Written by Greg Portmann
if nargin < 1
    global THERING
end
ATCavityIndex = findcells(THERING, 'Frequency');
CavityState = '';
PassMethod = '';
RF = [];
if isempty(ATCavityIndex)
    %disp('   No cavities were found in the lattice');
    [HarmonicNumber, RF] = getharmonicnumber;
    return
end
ATCavityIndex =ATCavityIndex(:)';
for ii = ATCavityIndex(:)'
    if strcmpi(THERING{ii}.PassMethod, 'DriftPass') || strcmpi(THERING{ii}.PassMethod, 'IdentityPass')
        CavityState = strvcat(CavityState,'Off');
    else
        CavityState = strvcat(CavityState,'On');
    end
    PassMethod = strvcat(PassMethod, THERING{ii}.PassMethod);
    RF =  [RF; THERING{ii}.Frequency];
end
ATCavityIndex = ATCavityIndex(:);
if nargout >= 5
    if isfield(THERING{ATCavityIndex(1)}, 'HarmonicNumber')
        HarmonicNumber = THERING{ATCavityIndex(1)}.HarmNumber;
    else
        HarmonicNumber = [];
    end
end