function mml2edm_mps(Directory)

% Setup = {
%     'Setpoint',       'Setpoint',    70
%     'Monitor',        'Monitor',     70
%     'Voltage',        'Voltage',     70
%     'BulkVoltage',    'B-Voltage',   70
%    %'RampRate',       'RampRate',    70
%    %'Ready',          'Rdy',         30
%     'On',             'On',          30
%     'OnControl',      'OnControl',   70 
%     'BulkOn',         'BOn',         30
%     'BulkControl',    'BulkControl', 80 
%    %'Reset',          'Reset',       65
%     'RelatedDisplay', 'More Info',   80
%    };
% 
% Fields       = Setup(:,1);
% ColumnLabels = Setup(:,2);
% ColumnWidth  = Setup(:,3);



DirStart = pwd;

if nargin < 1
    if ispc
        cd \\Als-filer\physbase\hlc\GTB
    else
        cd /home/als/physbase/hlc/GTB
    end
else
    cd(Directory);
end


WindowLocation = [120 60];
FileName = 'MML2EDM_GTB_MPS.edl';
TitleBar = 'GTB Magnet Power Supplies';
GoldenSetpoints = 'On';
MotifWidget = 'Off';
SP_AM = 'On';
ChannelLabelWidth = 70;



% [x11, y11]= mml2edm('HCM', ...
%     'FileName', FileName, ...
%     'MoreButton', 'On', ...
%     'Fields', Fields, ...
%     'RelatedDisplayCommand', 'CaenA36xx.edl', ...
%     'xStart', XBuffer, ...
%     'yStart', 1, ...
%     'BC_SetAllButton', 'On', ...
%     'SP_SetAllButton', 'On', ...
%     'ColumnLabels', ColumnLabels, ...
%     'ColumnWidth', ColumnWidth, ...
%     'ChannelLabelWidth', ChannelLabelWidth, ...
%     'WindowLocation', [120 60], ...
%     'GoldenSetpoints', GoldenSetpoints, ...
%     'MotifWidget', MotifWidget, ...
%     'TitleBar', TitleBar);

[x11, y11]= mml2edm('HCM', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'xStart', 3, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'Precision', 5, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'BCButtonType', 'Choice', ...   % Reset or Choice, Double???
    'TableTitle', 'Horizontal Correctors', ...
    'TitleBar', TitleBar);


[x21, y21]= mml2edm('VCM', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', 3, ...
    'yStart', y11+5, ...
    'SP-AM', SP_AM, ...
    'Precision', 5, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TableTitle', 'Vertical Correctors', ...
    'TitleBar', TitleBar);

[x31, y31]= mml2edm('MOD', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', 3, ...
    'yStart', y21+0, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TableTitle', 'Modulators', ...
    'Fields', {'Setpoint','Monitor','Klystron','HVControl','Trigger'}, ...
    'ChannelType', {'Monitor', 'Monitor', 'Monitor', 'Monitor', 'Boolean Monitor'}, ...
    'ColumnWidth', {70 70 70 75 45}, ...
    'TitleBar', TitleBar);

[x41, y41]= mml2edm('SHB', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', 3, ...
    'yStart', y31+5, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TableTitle', 'Subharmonic Buncher', ...
    'Fields', {'HV','HVControl','Phase','PhaseControl','Ready','On'}, ...
    'ChannelType', {'Monitor', 'Monitor', 'Monitor', 'Monitor', 'Boolean Monitor', 'Boolean Monitor'}, ...
    'ColumnWidth', {70 70 70 95 30 30}, ...
    'TitleBar', TitleBar);


%  Not using SP-AM column because AM is not really working
[x12, y12]= mml2edm('BEND', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', x11+25, ...
    'yStart', 5, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TableTitle', 'Bends', ...
    'TitleBar', TitleBar);


%  Not using SP-AM column because AM is not really working
[x22, y22]= mml2edm('SOL', ...
    'SP_SetAllButton', 'On', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', x11+25, ...
    'yStart', y12+0, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'Fields', {'Setpoint','Monitor','SP-AM','Ready','On','OnControl'}, ...
    'TableTitle', 'Solenoids', ...
    'TitleBar', TitleBar);


%  Not using SP-AM column because quadrupoles have "," in the name
[x32, y32]= mml2edm('Q', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', x11+25, ...
    'yStart', y22+0, ...
    'Precision', 5, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TableTitle', 'Quadrupoles', ...
    'TitleBar', TitleBar);


[x42, y42]= mml2edm('BuckingCoil', ...
    'SP_SetAllButton', 'On', ...
    'FileName', FileName, ...
    'MoreButton', 'On', ...
    'Append', ...
    'xStart', x11+25, ...
    'yStart', y32+0, ...
    'SP-AM', SP_AM, ...
    'Precision', 5, ...
    'WindowLocation', [120 60], ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'ChannelLabelWidth', ChannelLabelWidth, ...
    'TableTitle', 'Bucking Coil', ...
    'TitleBar', TitleBar);

   % 'Fields', {'Setpoint','Monitor','SP-AM','Ready','On','OnControl'}, ...
%visPv = '';
%colorPv = '';    

                   
% Add push buttons for other applications
edm_addinjectorbuttons(0, y42+20, FileName);


xmax = max([x11 x21 x12 x41 x22 x31 x32 x42]);
ymax = max([y11 y21 y12 y41 y22 y31 y32 y42]);
% if  ymax > 1200 %  I'm not sure when the slider appears
%     % To account for a window slider
%     Width  = xmax+30;
%     Height = 1220;
% else
     Width  = xmax + 10;
     Height = ymax + 20+40;
% end

%EDMExitButton(xmax-68, 3, 'FileName', FileName, 'ExitProgram');

Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



cd(DirStart);


