function srsetup
%SRSETUP - GUI for doing storage ring setup
% GUI for doing storage ring setup
%
% Written by Laurent S. Nadolski

checkforao;

%Clear previous ORBIT figure
orbfig = findobj(allchild(0),'tag','srsetup'); 

if ~isempty(orbfig), delete(orbfig); end

kmax = 11; % button number

height = 10 + kmax*30 + 30; %670;
a = figure('Color',[0.8 0.8 0.8], ...
    'Interruptible', 'on', ...   
    'HandleVisibility','off', ...
    'MenuBar','none', ...
    'Name', 'Ring Command Launcher', ...
    'NumberTitle','off', ...
    'Units','pixels', ...
    'Position',[5 70 210*4 height], ...
    'Resize','off', ...
    'Tag','srsetup');

height = height - 35;

for k = 1:kmax,
    b1(k) = uicontrol('Parent',a, ...
        'Position',[3 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

for k = 1:kmax,
    b2(k) = uicontrol('Parent',a, ...
        'Position',[3 + 210 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

for k = 1:kmax,
    b3(k) = uicontrol('Parent',a, ...
        'Position',[3 + 210*2 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

for k = 1:kmax,
    b4(k) = uicontrol('Parent',a, ...
        'Position',[3 + 210*3 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

set(b1(1), 'Callback','setpathsoleil(''StorageRing'');', 'String','Soleilinit','BackgroundColor','g');
set(b1(2), 'Callback','refreshthering', 'String','Recharger la maille');
set(b1(3), 'Callback','plotfamily', 'String','Plotfamily');
set(b1(4), 'Callback','disp([''   Fichiers de Consignes;'']); configgui;;', 'String','Fichiers de Consignes');
set(b1(5), 'Callback','disp([''   Ringcycling;'']);Ringcycling', 'String','Cyclage');
set(b1(6), 'Callback','disp([''   Timing;'']); synchro_injecteur7;', 'String','Synchronisation définitive');
set(b1(7), 'Callback','steerette', 'String','Steerette');
set(b1(8), 'Callback','energytunette', 'String', 'Energytunette');
set(b1(9), 'Callback','fourturnalgorithm', 'String', 'Algo 4 tours');


set(b2(1), 'Callback','figure;plotorbit;', 'String','Plotorbit');
set(b2(2), 'Callback','solorbit', 'String','solorbit');
set(b2(3), 'Callback','figure; disp([''   setorbit;'']); setorbit(''Display'');', 'String','Correction d''orbite');
set(b2(4), 'Callback','disp([''   measbpmresp;'']); measbpmresp;', 'String','Generate BPM Response Matrix');
set(b2(5), 'Callback','figure; disp([''   rmdisp;'']); rmdisp(''BPMx'',''Display'');', 'String','Find New RF Frequency (LS Fit)');
set(b2(6), 'Callback','figure; disp([''   findrf;'']); findrf;', 'String','Find New RF Frequency (Dot Product)');
set(b2(7), 'Callback','disp([''   gettune;'']); gettune(''Display'');', 'String','Get Tunes');
set(b2(8), 'Callback','disp([''   settune;'']); settune;', 'String','Set Tunes');
set(b2(9), 'Callback','getbpmsum;', 'String','Signal Somme (1er tour)');
set(b2(10), 'Callback','nombre_onde_ans;', 'String','FFT Tour par Tour');
set(b2(11), 'Callback','bpmconfigurator;', 'String','Configuration BPM');

set(b3(1), 'Callback','tango_staticdb_config', 'String','DBT config','BackgroundColor','r');
set(b3(2), 'Callback','tango_archiving_config', 'String','Archivage');
set(b3(3), 'Callback','disp([''   meastuneresp;'']); meastuneresp;', 'String','Generate Tune Response Matrix');
set(b3(4), 'Callback','figure; disp([''   measdisp;'']); measdisp;', 'String','Measure Dispersion');
set(b3(5), 'Callback','figure; disp([''   measchro;'']); measchro(''Physics'');', 'String','Measure The Chromaticity');
set(b3(6), 'Callback','disp([''   stepchro;'']); stepchro(''Physics'');', 'String','Step The Chromaticity');
set(b3(7), 'Callback','figure; disp([''   measchroresp;'']); measchroresp;', 'String','Generate Chromaticity Response Matrix');
set(b3(8), 'Callback','disp([''   getmachineconfig;'']); getmachineconfig(''Archive'');', 'String','Save Lattice');
set(b3(9), 'Callback','disp([''   setmachineconfig;'']); setmachineconfig;', 'String','Load Lattice');
set(b3(10), 'Callback','disp([''   intlat;'']); intlat;', 'String','Interactive Lattice');

set(b4(1), 'Callback','', 'String','Cellule 13','BackgroundColor','c');
%set(b4(2), 'Callback','quadcell13(''Off'')', 'String','ETEINDRE');
%set(b4(3), 'Callback','quadcell13(''On'')', 'String','ALLUMER');
set(b4(4), 'Callback','quadcell13(''Reset'')', 'String','RESET');
set(b4(5), 'Callback','quadcell13(''State'')', 'String','ETAT');
%set(b4(6), 'Callback','tango_group_command_inout2(getfamilydata(''CycleQC13'',''GroupId''),''Start'',0,0)', ...
%    'String','CYCLAGE (sans config)');
set(b4(7), 'Callback','getbpmagcgain', 'String','BPM gain AGC');
set(b4(8), 'Callback','plotquad;', 'String','Etat QUAD');
%set(b4(9), 'Callback','monmags;', 'String','Statistiques sur alim');


b = uicontrol('Parent',a, ...
    'Callback','close all', ...
    'String','Close All Figures', ...
    'Position',[3 height-kmax*30 204 27], ...
    'Userdata',[], ...
    'Interruptible', 'off', ...   
    'Tag','button2');

% b = uicontrol('Parent',a, ...
%     'Callback',[ ...
%         'if isempty(get(findobj(gcbf,''Tag'',''button3''),''Userdata''));' ...
%         '  disp('' '');', ...
%         '  disp(''  A diary records everything echoed to the matlab command window.'');pause(0);', ...
%         '  [filename, pathname] = uiputfile(''*.txt'', ''Choose a dairy filename.'');', ...
%         '  if filename==0;', ...
%         '     return;', ...
%         '  else;', ...
%         '     filename = [pathname filename];', ...
%         '  end;', ...
%         '  eval([''diary '', filename]);', ...
%         '  set(findobj(gcbf,''Tag'',''button3''),''Userdata'',filename);' ...
%         '  set(findobj(gcbf,''Tag'',''button3''),''String'',''Stop Diary'');' ...
%         'else;   ', ...
%         '  disp('' '');', ...
%         '  diary off;', ...
%         '  disp([''  Diary file '',get(findobj(gcbf,''Tag'',''button3''),''Userdata''),'' closed.'']);', ...
%         '  set(findobj(gcbf,''Tag'',''button3''),''Userdata'',[]);' ...
%         '  set(findobj(gcbf,''Tag'',''button3''),''String'',''Start/Append Diary'');' ...
%         'end;   ', ...
%     ], ...
%     'String','Start/Append Diary', ...
%     'Position',[3 65 204 27], ...
%     'Userdata',[], ...
%     'Interruptible', 'off', ...   
%     'Tag','button3');
