%MEXCOMMAND Make mca.dll and timereval.dll
%
cd C:\MATLAB6p5\toolbox\mcanew\mca
mex mca.cpp MCAError.cpp Channel.cpp ChannelAccess.cpp ...
            C:\epics\base\lib\win32-x86\Com.lib ...
            C:\epics\base\lib\win32-x86\ca.lib ...
            C:\borland\bcc55\lib\ws2_32.lib ...
            -DDB_TEXT_GLBLSOURCE -DBCC -DEPICS_DLL_NO ...     
            -IC:\epics\base\include ...
            -IC:\epics\base\include\os\WIN32 ...
            -v
mex timereval.cpp -v