%MEXCOMMAND Make mca.mexglx from mcamain.cpp

cd /matlab/toolbox/mca
mex mca.cpp MCAError.cpp Channel.cpp ChannelAccess.cpp ...
    /epics/base/lib/linux-x86/libCom.so ...
    /epics/base/lib/linux-x86/libca.so ...
    -DDB_TEXT_GLBLSOURCE -DGCC -DEPICS_DLL_NO ...     
    -I/epics/base/include ...
    -I/epics/base/include/os/Linux ...
    -v


