function mml2edm_mps(Directory)

DirStart = pwd;

if nargin < 1
    if ispc
        cd \\Als-filer\physbase\hlc\SR
    else
        cd /home/als/physbase/hlc/SR
    end
else
    cd(Directory);
end


EyeAide = 'On';
WindowLocation = [120 60];
GoldenSetpoints = 'On';
MotifWidget = 'Off';
SP_AM = 'On';


%%%%%%%%
% Main %
%%%%%%%%
WindowLocation = [120 60];
FileName = 'MML2EDM_MPS.edl';
TitleBar = 'Magnet Power Supplies';
fprintf('   Building %s (%s)\n', TitleBar, FileName);

Width = 20;
Height = 20;
Color = 20; % Red

% Start the output file
fid = fopen(FileName, 'w', 'b');
[Header, TitleBar] = EDMHeader('TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', 1310, 'Height', 100);
WriteEDMFile(fid, Header);

n = 0;

% HCM
Family = 'HCM';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay(['/home/als/physbase/hlc/SR/MML2EDM_',Family], x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% VCM
Family = 'VCM';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay(['/home/als/physbase/hlc/SR/MML2EDM_',Family], x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% SQSF
Family = 'SQSF';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_SQSF_SQSD', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% SQSD
Family = 'SQSD';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_SQSF_SQSD', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end


% QF
Family = 'QF';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_QF_QD', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% QD
Family = 'QD';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_QF_QD', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% QDA
Family = 'QDA';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_MAIN_MPS', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% QFA
Family = 'QFA';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_MAIN_MPS', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field, family2dev(Family, Field, 1, 1));
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% BEND
Family = 'BEND';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_MAIN_MPS', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field, family2dev(Family, Field, 1, 1));
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end


% SF
Family = 'SF';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_MAIN_MPS', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field, family2dev(Family, Field, 1, 1));
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% SD
Family = 'SD';
Field = 'On';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_MAIN_MPS', x, y, 'Width', 75, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field, family2dev(Family, Field, 1, 1));
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+37-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end


% QFA Shunt
Family = 'QFA';
n = n + 1;
x = n*4+(n-1)*75;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_QFA_SHUNTS', x, y, 'Width', 120, 'Height', 20, 'ButtonLabel', 'QFA Shunt', 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+60-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, 'Shunt1');
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+60-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'NotVisibleIf', deblank(ChannelNames(i,:))));
end

% Pile up all the On BMs
ChannelNames = family2channel(Family, 'Shunt2');
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+60-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'NotVisibleIf', deblank(ChannelNames(i,:))));
end


% HCMCHICANE
Family = 'HCMCHICANE';
Field = 'On';
x = (n+1)*4+(n-1)*75+120;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_CHICANES', x, y, 'Width', 150, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+75-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+75-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

% VCMCHICANE
Family = 'VCMCHICANE';
Field = 'On';
x = (n+2)*4+(n-1)*75+120+150;
y = 4;
% Related display
WriteEDMFile(fid, EDMRelatedDisplay('/home/als/physbase/hlc/SR/MML2EDM_CHICANES', x, y, 'Width', 150, 'Height', 20, 'ButtonLabel', Family, 'CommandLabel', ''));

% Put green on the bottom
WriteEDMFile(fid, EDMRectangle(x+75-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', 15, 'FillColor', 15));

% Pile up all the On BMs
ChannelNames = family2channel(Family, Field);
for i = 1:size(ChannelNames,1)
    WriteEDMFile(fid, EDMRectangle(x+75-Width/2, y+25, 'Width', Width, 'Height', Height, 'LineColor', Color, 'FillColor', Color, 'VisibleIf', deblank(ChannelNames(i,:))));
end

fclose(fid);

% Update the header
% xmax = max([x11 x12]);
% ymax = max([y11 y12]);
% Width  = xmax + 10;
% Height = ymax + 10;
% Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



%%%%%%%%%%%%%%%%%%%%%%%
% Main Power Supplies %
%%%%%%%%%%%%%%%%%%%%%%%
WindowLocation = [120 60];
FileName = 'MML2EDM_MAIN_MPS.edl';
TitleBar = 'SR - Magnet Power Supplies';
fprintf('   Building %s (%s)\n', TitleBar, FileName);


[x11, y11]= mml2edm('BEND', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'BEND', ...
    'TitleBar', TitleBar);

% Add the "More Details" button
yStart = 54;
yHeight = 20;

fid = fopen(FileName, 'r+', 'b');
status = fseek(fid, 0, 'eof');
% WriteEDMFile(fid, EDMShellCommand( ...
%     '/home/als/physbase/hlc/SR/runSRBendDetails.sh', x11, yStart, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More Details', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
     '/home/als/physbase/hlc/SR/SRBendDetails.edl', x11, yStart, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));

% WriteEDMFile(fid, EDMShellCommand( ...
%     '/home/als/physbase/hlc/SR/SuperBend/runSuperBendDetails.sh 04', x11, yStart + 1*yHeight + 2, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More Details', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SuperBend/SuperBendDetails', x11, yStart + 1*yHeight + 2, 'Width', 100, 'Height', yHeight, 'Macro', 'Sector=04', 'ButtonLabel', 'More ...', 'CommandLabel', ''));

% WriteEDMFile(fid, EDMShellCommand( ...
%     '/home/als/physbase/hlc/SR/SuperBend/runSuperBendDetails.sh 08', x11, yStart + 2*yHeight + 4, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More Details', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SuperBend/SuperBendDetails', x11, yStart + 2*yHeight + 4, 'Width', 100, 'Height', yHeight, 'Macro', 'Sector=08', 'ButtonLabel', 'More ...', 'CommandLabel', ''));

%WriteEDMFile(fid, EDMShellCommand( ...
%    '/home/als/physbase/hlc/SR/SuperBend/runSuperBendDetails.sh 12', x11, yStart + 3*yHeight + 6, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More Details', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SuperBend/SuperBendDetails', x11, yStart + 3*yHeight + 6, 'Width', 100, 'Height', yHeight, 'Macro', 'Sector=12', 'ButtonLabel', 'More ...', 'CommandLabel', ''));
fclose(fid);


x11 = x11 + 100;


[x21, y21]= mml2edm('SF', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y11+20, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SF', ...
    'TitleBar', TitleBar);


[x12, y12]= mml2edm('QFA', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x11+25, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'QFA', ...
    'TitleBar', TitleBar);

[x22, y22]= mml2edm('QDA', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x11+25, ...
    'yStart', y12+10, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'QDA', ...
    'TitleBar', TitleBar);

[x31, y31]= mml2edm('SD', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y21+20, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SD', ...
    'TitleBar', TitleBar);




fid = fopen(FileName, 'r+', 'b');
status = fseek(fid, 0, 'eof');
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR01SFDetails', x21, y11+74,   'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR01SDDetails', x21, y21+34 + 2*yHeight, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR01QFADetails', x12, yStart,                 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR04QFADetails', x12, yStart + 1*yHeight + 2, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR08QFADetails', x12, yStart + 2*yHeight + 4, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR12QFADetails', x12, yStart + 3*yHeight + 6, 'Width', 100, 'Height', yHeight, 'ButtonLabel', 'More ...', 'CommandLabel', ''));

x12 = x12 + 100;

fclose(fid);

xmax = max([x11 x21 x12 x22 x31]);
ymax = max([y11 y21 y12 y22 y31]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);




%%%%%%%%%%%
% QF & QD %
%%%%%%%%%%%
WindowLocation = [120 60];
FileName = 'MML2EDM_QF_QD.edl';
TitleBar = 'SR - QF & QD Magnet Power Supplies';
fprintf('   Building %s (%s)\n', TitleBar, FileName);

[x11, y11]= mml2edm('QF', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'QF', ...
    'TitleBar', TitleBar);

[x12, y12]= mml2edm('QD', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x11+45, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'QD', ...
    'TitleBar', TitleBar);


% Update the header
xmax = max([x11 x12]);
ymax = max([y11 y12]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



% MML2EDM_SEXTUPOLES
WindowLocation = [120 60];
FileName = 'MML2EDM_SEXTUPOLES.edl';
TitleBar = 'SR - Sextupole Magnet Power Supplies';
fprintf('   Building %s (%s)\n', TitleBar, FileName);


[x11, y11]= mml2edm('SF', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 8, ...
    'yStart', 3, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SF', ...
    'TitleBar', TitleBar);

[x12, y12]= mml2edm('SD', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x11+60, ...
    'yStart', 3, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SD', ...
    'TitleBar', TitleBar);

[x21, y21]= mml2edm('SHF', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 3, ...
    'yStart', max([y11 y12]+5), ...
    'SP-AM', SP_AM, ...
    'MoreButton', 'On', ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SHF', ...
    'TitleBar', TitleBar);

[x22, y22]= mml2edm('SHD', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x21+25, ...
    'yStart', max([y11 y12]+5), ...
    'SP-AM', SP_AM, ...
    'MoreButton', 'On', ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SHD', ...
    'TitleBar', TitleBar);

fid = fopen(FileName, 'r+', 'b');
status = fseek(fid, 0, 'eof');
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR01SFDetails', x11-180, 5, 'Width', 130, 'Height', 22, 'ButtonLabel', 'SF More ...', 'CommandLabel', ''));
WriteEDMFile(fid, EDMRelatedDisplay( ...
    '/home/als/physbase/hlc/SR/SR01SDDetails', x12-180, 5, 'Width', 130, 'Height', 22, 'ButtonLabel', 'SD More ...', 'CommandLabel', ''));

% Update the header
xmax = max([x11 x12 x21 x22]);
ymax = max([y11 y12 y21 y22]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



% SQSF & SQSD
WindowLocation = [120 60];
FileName = 'MML2EDM_SQSF_SQSD.edl';
TitleBar = 'SR - SQSF & SQSD Magnet Power Supplies';
fprintf('   Building %s (%s)\n', TitleBar, FileName);

[x11, y11]= mml2edm('SQSF', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0, ...
    'MoreButton', 'On', ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SQSF', ...
    'TitleBar', TitleBar);


[x21, y21]= mml2edm('SQSD', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y11+20, ...
    'MoreButton', 'On', ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SQSD', ...
    'TitleBar', TitleBar);

[x12, y12]= mml2edm('SQSHF', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', max([x11 x21])+15, ...
    'yStart', 0, ...
    'MoreButton', 'On', ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'SQSHF', ...
    'TitleBar', TitleBar);

[x22, y22]= mml2edm('SQEPU', ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', max([x11 x21])+15, ...
    'yStart', y12+10, ...
    'MoreButton', 'On', ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', 'Off', ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'EPU Skew Quadrupoles', ...
    'TitleBar', TitleBar);


% Update the header
xmax = max([x11 x12 x21 x22]);
ymax = max([y11 y12 y21 y22]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);


% HCM
WindowLocation = [120 60];
FileName = 'MML2EDM_HCM.edl';
TitleBar = 'SR - Horizontal Corrector Magnets';
fprintf('   Building %s (%s)\n', TitleBar, FileName);

%DeviceList = family2dev('HCM', 1, 1);
DeviceList = getcmlist('HCM', [1 2 3 4 5 6]);

%mml2edm('HCM', 'TitleBar', 'SR - Horizontal Corrector Magnets');
[x11, y11]= mml2edm('HCM', ...
    'DeviceList', DeviceList, ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'MoreButton', 'On', ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'BC_SetAllButton', 'On', ...
    'SP_SetAllButton', 'On', ...
    'TableTitle', 'HCM - Sectors 1-6', ...
    'TitleBar', TitleBar);

DeviceList = getcmlist('HCM', [7 8 9 10 11 12]);
[x12, y12]= mml2edm('HCM', ...
    'DeviceList', DeviceList, ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x11+45, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'MoreButton', 'On', ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'BC_SetAllButton', 'On', ...
    'SP_SetAllButton', 'On', ...
    'TableTitle', 'HCM - Sectors 7-12', ...
    'TitleBar', TitleBar);

% Update the header
xmax = max([x11 x12]);
ymax = max([y11 y12]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);


% VCM
WindowLocation = [120 60];
FileName = 'MML2EDM_VCM.edl';
TitleBar = 'SR - Vertical Corrector Magnets';
fprintf('   Building %s (%s)\n', TitleBar, FileName);

%DeviceList = family2dev('VCM', 1, 1);
DeviceList = getcmlist('VCM', [1 2 3 4 5 6]);

%mml2edm('HCM', 'TitleBar', 'SR - Horizontal Corrector Magnets');
[x11, y11]= mml2edm('VCM', ...
    'DeviceList', DeviceList, ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'MoreButton', 'On', ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'VCM - Sectors 1-6', ...
    'TitleBar', TitleBar);

DeviceList = getcmlist('VCM', [7 8 9 10 11 12]);
[x12, y12]= mml2edm('VCM', ...
    'DeviceList', DeviceList, ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', x11+45, ...
    'yStart', 0, ...
    'MoreButton', 'On', ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'VCM - Sectors 7-12', ...
    'TitleBar', TitleBar);

% Update the header
xmax = max([x11 x12]);
ymax = max([y11 y12]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



%%%%%%%%%%%%
% Chicanes %
%%%%%%%%%%%%
WindowLocation = [120 60];
FileName = 'MML2EDM_CHICANES.edl';
TitleBar = 'SR - Chicanes Magnets';
fprintf('   Building %s (%s)\n', TitleBar, FileName);

[x11, y11]= mml2edm('HCMCHICANE', ...
    'Fields', {'Setpoint','Monitor','RampRate','On','OnControl'}, ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'xStart', 0, ...
    'yStart', 0, ...
    'SP-AM', SP_AM, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'HCM Chicane', ...
    'TitleBar', TitleBar);

x12 = 0;
y12 = y11;
% Removed since they should be off
% [x12, y12]= mml2edm('VCMCHICANE', ...
%     'Fields', {'Setpoint','Monitor','RampRate','On','OnControl'}, ...
%     'EyeAide', EyeAide, ...
%     'FileName', FileName, ...
%     'Append', ...
%     'xStart', 0, ...
%     'yStart', y11+25, ...
%     'WindowLocation', WindowLocation, ...
%     'GoldenSetpoints', 'Off', ...
%     'MotifWidget', MotifWidget, ...
%     'TableTitle', 'VCM Chicane', ...
%     'TitleBar', TitleBar);

[x13, y13]= mml2edm('HCMCHICANEM', ...
    'Fields', {'Setpoint', 'Monitor'}, ...
    'EyeAide', EyeAide, ...
    'FileName', FileName, ...
    'Append', ...
    'xStart', 0, ...
    'yStart', y12+25, ...
    'WindowLocation', WindowLocation, ...
    'GoldenSetpoints', GoldenSetpoints, ...
    'MotifWidget', MotifWidget, ...
    'TableTitle', 'HCM Motor Chicane', ...
    'TitleBar', TitleBar);

% Update the header
xmax = max([x11 x12 x13]);
ymax = max([y11 y12 y13]);
Width  = xmax + 10;
Height = ymax + 10;
Header = EDMHeader('FileName', FileName, 'TitleBar', TitleBar, 'WindowLocation', WindowLocation, 'Width', Width, 'Height', Height);



cd(DirStart);



% if  ymax > 1200 %  I'm not sure when the slider appears
%     % To account for a window slider
%     Width  = xmax+30;
%     Height = 1220;
% else
%     Width  = xmax + 10;
%     Height = ymax + 10;
% end



function WriteEDMFile(fid, Header)

for i = 1:length(Header)
    fprintf(fid, '%s\n', Header{i});
end
fprintf(fid, '\n');

