function srsetup()
% GUI for doing storage ring setup
%

% For the compiler
%#function gettune settune steptune 
%#function setorbitdefault
%#function findrf2 findrf
%#function measchro
%#function measdisp
%#function setbumps
%#function bumpinj
%#function ffgettbl
%#function ffanal
%#function setskewq
%#function measbpmresp
%#function plotorbit
%#function getmachineconfig setmachineconfig
%#function plotlattice
%#function srramp
%#function setskewq
%#function buildramptables



checkforao;

GLOBAL_SR_MODE_TITLE = getfamilydata('OperationalMode');

GeV = getenergy;


disp(['  ********************************************']);
disp(['  **  Storage ring setup program (srsetup)  **']);
disp(['  ********************************************']);
if ~isempty('GeV')
    disp(['  If the SR energy is not ',num2str(GeV),' GeV, rerun alsinit.']);
else
    disp(['  SR energy is unknown, run alsinit before continuing.']);
end
disp('  The typical mode of operation for setup is the following.  ');
disp('          1.  Multibunch mode.');
disp('          2.  Multibunch feedbacks off with the appropriate RF cavity temperatures.');
disp('          3.  Current range: 35-45 mAmps for orbit correction, >30 mAmps for tune measuring.');
disp('          4.  Production corrector magnet set.');
disp('          5.  Bumps off and BTS 3 and 4 set to zero current.');
disp('          6.  FF disabled.');
disp('          7.  Gap Control disabled.');
disp('          8.  BPMs calibrated at appropriate energy.');
disp('              (The BPMs need ~45 minutes to cool after full-current operations.)');
disp(['  ']);



a = figure('Color',[0.8 0.8 0.8], ...
    'Interruptible', 'on', ...
    'HandleVisibility','off', ...
    'MenuBar','none', ...
    'Name',sprintf('%s SETUP', GLOBAL_SR_MODE_TITLE), ...
    'NumberTitle','off', ...
    'Units','pixels', ...
    'Position',[5 70 210 695], ...
    'Resize','off', ...
    'Tag','srsetup');

b = uicontrol('Parent',a, ...
    'Callback','setorbitdefault;', ...
    'Interruptible', 'off', ...
    'String','Orbit Correction', ...
    'Position',[3 665 204 27], ...
    'Tag','button24');

%b = uicontrol('Parent',a, ...
%	'Callback','findqfa;', ...
%  'Interruptible', 'off', ...
%	'String','Find New QFA Current', ...
%   'Position',[3 665 204 27], ...
%   'Tag','button23');

b = uicontrol('Parent',a, ...
    'Callback','RF = findrf2;', ...
    'Interruptible', 'off', ...
    'String','New RF Frequency (findrf2/analcm)', ...
    'Position',[3 635 204 27], ...
    'Tag','button22');

b = uicontrol('Parent',a, ...
    'Callback','measchro(''Physics'');', ...
    'Interruptible', 'off', ...
    'String','Measure Chromaticity', ...
    'Position',[3 605 204 27], ...
    'Tag','button21');

b = uicontrol('Parent',a, ...
    'Callback','gettune(''Display'');', ...
    'Interruptible', 'off', ...
    'String','Get Tunes', ...
    'Position',[3 575 204 27], ...
    'Tag','button20');

b = uicontrol('Parent',a, ...
    'Callback','settune;', ...
    'Interruptible', 'off', ...
    'String','Set Tunes', ...
    'Position',[3 545 204 27], ...
    'Tag','button19');

b = uicontrol('Parent',a, ...
    'Callback','measdisp(''Physics'');', ...
    'Interruptible', 'off', ...
    'String','Measure Dispersion', ...
    'Position',[3 515 204 27], ...
    'Tag','button18');

b = uicontrol('Parent',a, ...
    'Callback','setskewq;', ...
    'Interruptible', 'off', ...
    'String','Set Skew Quadrupole', ...
    'Position',[3 485 204 27], ...
    'Tag','button17');

b = uicontrol('Parent',a, ...
    'Callback','setbumps;', ...
    'Interruptible', 'off', ...
    'String','Add User Bumps', ...
    'Position',[3 455 204 27], ...
    'Tag','button16');

b = uicontrol('Parent',a, ...
    'Callback','bumpinj;', ...
    'Interruptible', 'off', ...
    'String','Add Injection Bump', ...
    'Position',[3 425 204 27], ...
    'Tag','button15');

b = uicontrol('Parent',a, ...
    'Callback','srramp;', ...
    'Interruptible', 'on', ...
    'String','SR Ramp Menu', ...
    'Position',[3 395 204 27], ...
    'Tag','button14');

b = uicontrol('Parent',a, ...
    'Callback','ffgettbl;', ...
    'Interruptible', 'off', ...
    'String','Generate Feed Forward Table', ...
    'Position',[3 365 204 27], ...
    'Tag','button13');

b = uicontrol('Parent',a, ...
    'Callback','fftest;', ...
    'Interruptible', 'off', ...
    'String','Test A Feed Forward Table', ...
    'Position',[3 335 204 27], ...
    'Tag','button12');

b = uicontrol('Parent',a, ...
    'Callback','ffanal;', ...
    'Interruptible', 'off', ...
    'String','Analyze a Feed Forward Table', ...
    'Position',[3 305 204 27], ...
    'Tag','button11');

b = uicontrol('Parent',a, ...
    'Callback','measbpmresp;', ...
    'Interruptible', 'off', ...
    'String','Generate Response Matrix', ...
    'Position',[3 275 204 27], ...
    'Tag','button10');

b = uicontrol('Parent',a, ...
    'Callback','figure; plotorbit(''Golden'');', ...
    'Interruptible', 'off', ...
    'String','Plot Orbit w.r.t. Golden', ...
    'Position',[3 245 204 27], ...
    'Tag','button9');

b = uicontrol('Parent',a, ...
    'Callback','figure; plotorbit(''Offset'');', ...
    'Interruptible', 'off', ...
    'String','Plot Orbit w.r.t. Offset', ...
    'Position',[3 215 204 27], ...
    'Tag','button8');

b = uicontrol('Parent',a, ...
    'Callback','figure;plotlattice(''Golden'');', ...
    'Interruptible', 'off', ...
    'String','Plot Lattice', ...
    'Position',[3 185 204 27], ...
    'Tag','button7');

b = uicontrol('Parent',a, ...
    'Callback','getmachineconfig;', ...
    'Interruptible', 'off', ...
    'String','Save Lattice', ...
    'Position',[3 155 204 27], ...
    'Tag','button6');

b = uicontrol('Parent',a, ...
    'Callback','buildramptables;', ...
    'Interruptible', 'off', ...
    'String','Build Ramptables', ...
    'Position',[3 125 204 27], ...
    'Tag','button5');

b = uicontrol('Parent',a, ...
    'Callback','setmachineconfig;', ...
    'Interruptible', 'off', ...
    'String','Load Lattice', ...
    'Position',[3 95 204 27], ...
    'Tag','button4');

b = uicontrol('Parent',a, ...
    'Callback',[ ...
    'if isempty(get(findobj(gcbf,''Tag'',''button3''),''Userdata''));' ...
    '  disp('' '');', ...
    '  disp(''  A diary records everything echoed to the matlab command window.'');pause(0);', ...
    '  [filename, pathname] = uiputfile(''*.txt'', ''Choose a dairy filename.'');', ...
    '  if filename==0;', ...
    '     return;', ...
    '  else;', ...
    '     filename = [pathname filename];', ...
    '  end;', ...
    '  eval([''diary '', filename]);', ...
    '  set(findobj(gcbf,''Tag'',''button3''),''Userdata'',filename);' ...
    '  set(findobj(gcbf,''Tag'',''button3''),''String'',''Stop Diary'');' ...
    'else;   ', ...
    '  disp('' '');', ...
    '  diary off;', ...
    '  disp([''  Diary file '',get(findobj(gcbf,''Tag'',''button3''),''Userdata''),'' closed.'']);', ...
    '  set(findobj(gcbf,''Tag'',''button3''),''Userdata'',[]);' ...
    '  set(findobj(gcbf,''Tag'',''button3''),''String'',''Start/Append Diary'');' ...
    'end;   ', ...
    ], ...
    'Interruptible', 'off', ...
    'String','Start/Append Diary', ...
    'Position',[3 65 204 27], ...
    'Userdata',[], ...
    'Tag','button3');


b = uicontrol('Parent',a, ...
    'Callback','close all', ...
    'Interruptible', 'off', ...
    'String','Close All Figures', ...
    'Position',[3 35 204 27], ...
    'Userdata',[], ...
    'Tag','button2');

b = uicontrol('Parent',a, ...
    'Callback','diary off; close(get(findobj(gcbf,''Tag'',''button1''),''Userdata''));', ...
    'Interruptible', 'off', ...
    'Position',[3 5 204 27], ...
    'String','CLOSE', ...
    'Userdata',a, ...
    'Tag','button1');

